#!/bin/bash
#
# 2016 WeakNet Labs, weaknetlabs@gmail.com
#  Douglas Berdeaux
#
# Ihave no idea why this needs to be a "2" since I used a regexp
if [ $(ps aux | grep -iE '[w]t7'|wc -l) -gt 3 ]; then
 killall wt7-weatherd # kill itself
fi
while [ 1 ];do
 get-weather.sh
 sleep 1800
done;
